### ISSUE TITLE
Support paging of search results

### ISSUE THREAD

**Issue by wabson** [Alfresco/alfresco-ng2-components#1014]
Currently only the first 50 search results are displayed in the list of results. We should allow users to use paging to see additional results.

**Comment by magemello** [comment]
Let's use the datatable

**Comment by hashraf88** [comment]
1. Instead of last page of results the below screenshot is displayed 

![screen shot 2017-01-27 at 14 49 54](https://cloud.githubusercontent.com/assets/13200338/22374951/1d2d5e9e-e4a0-11e6-8c15-db97fa666c0b.png)
**video to show issue 1**
[lastPage.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/735481/lastPage.mp4.zip)

2. The total count of documents `on the page` is incorrect, in the below example cannot have item 80 of 78. 

![screen shot 2017-01-27 at 14 57 49](https://cloud.githubusercontent.com/assets/13200338/22375449/fe0ddb40-e4a1-11e6-85eb-d6ec19ff0af5.png)

**Comment by hashraf88** [comment]
Issues above reported in #1557 and #1558
