### ISSUE TITLE
Update to webpack 2

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1569]
**Type of issue:**  (check with "[x]")
```
- [ x ] New feature request
- [ ] Bug  
- [ ] Support request
```
**Current behavior:**

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
As part of the migration we should move from `awesome-typescript-loader` to `ts-loader`. That should solve the problems we have related to pinned TypeScript version (due to loader problems) and high RAM consumption problems when watching linked projects.

See more details [here](https://webpack.js.org/guides/webpack-and-typescript/)

**Comment by DenisVuyka** [comment]
This task will also involve:

- migrate unit tests to webpack 2
- migrate code coverage support to webpack 2
