### ISSUE TITLE
Activiti Analytics - Should provide a way to hide the analytics parameters component

### ISSUE THREAD

**Issue by mauriziovitale** [Alfresco/alfresco-ng2-components#1634]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**

There is no way to hide the analitics parameter when you are using the analytics component
**Expected behavior:**

As a developer I'd like to have a property to show or hide the analytics parameters inside the analytics component. 
In this way I can declare something like that in my demo app 
<analytics [appId]=“1” [reportId]=“123” [hideParameters]="true">

The analytics component will show only the charts
<img width="597" alt="screen shot 2017-02-15 at 11 33 58" src="https://cloud.githubusercontent.com/assets/14923305/22972706/b808047e-f372-11e6-85ab-b81575f854a3.png">

Instead of the parameters and the charts
<img width="585" alt="screen shot 2017-02-15 at 11 37 10" src="https://cloud.githubusercontent.com/assets/14923305/22972807/20dcfd60-f373-11e6-8d6b-a1de7952a269.png">

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by hashraf88** [comment]
1. When going into any report initially the settings should be displayed, not hidden, as otherwise the user is met with a virtually a blank page with no indication as to what actions are required. 

2. When settings are hidden the text 'Fill in parameters to generate your report' should also be hidden 
<img width="507" alt="screen shot 2017-02-23 at 14 19 29" src="https://cloud.githubusercontent.com/assets/13200338/23262742/b4225cda-f9d3-11e6-9414-1531e1399e3c.png">

3. Within the process definition heat map, should dropdown displayed also be hidden? 
![screen shot 2017-02-23 at 14 34 51](https://cloud.githubusercontent.com/assets/13200338/23263257/9ba77ef4-f9d5-11e6-89b1-076c9570258e.png)

**Comment by mauriziovitale** [comment]
1 - We can also add some logic to show the parameters just in case the form is not filled up 
2 - I disagree. I think the message explains to the user what it should do.
3 - The parameter that you highlight is part of the "analytics-generator-render" so is not part of the analytics-parameters
