### ISSUE TITLE
IE 11 crash on beta3

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#2541]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
After installing 1.10 beta3 IE 11 crashes after loading the application

**Steps to reproduce the issue:**
Install beta 3
load the application with multiple tasks
navigate between tasks by clicking on each one.
browser crashes in mshtml.dll windows 10 and 7

**Component name and version:** 
ADF components 1.10 beta 3

**Browser and version:** 
IE11
 
**Node version (for build issues):**  
node 8.1.4
npm 5.3.0

**Comment by navonodt** [comment]
is there any status on this?

**Comment by DenisVuyka** [comment]
Can you check beta5 that is out already?

**Comment by navonodt** [comment]
still happens on beta 5...

**Comment by navonodt** [comment]
the crash occures when selecting rows in the task list specifically if that helps

**Comment by navonodt** [comment]
actually with further testing it's on task details that triggers the crash not the list

**Comment by tdonovancsra** [comment]
FYI,  tried the alpha and still getting the crash

**Comment by eromano** [comment]
@tdonovancsra just merged the fix and also tested it against IE11 the problem was about ngfor that seems not work 100% in ie11 especially if used in combination with ng-container and objects array:
![screen_capture](https://user-images.githubusercontent.com/1030050/33155943-be39f7c4-cfec-11e7-9a88-9293775af8c0.gif)
this is the commit: https://github.com/Alfresco/alfresco-ng2-components/commit/d2e1dc5aed8fd57fbf7488f5b839c67fc92f05a3

**Comment by tdonovancsra** [comment]
@eromano thanks!  We had finally narrowed it down to this component and took it out and wrote our own as we can't upgrade this close to our release but it's good to know the cause.  Thanks for looking into this.  We knew it was related but not the exact cause
