### ISSUE TITLE
Support for facetIntervals in AFD search component

### ISSUE THREAD

**Issue by HansDeBal** [Alfresco/alfresco-ng2-components#3557]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**New feature request:**
The current search filter component doesn't support facetIntervals (see public search API). For our current project we need to define a facet call "Timing" which should contain values like "This week", "Next month",... With the current search filter womponent this is not possible. Please add this feature. I also created a case dor this with Alfresco support, see case nr 00967571.

**Comment by HansDeBal** [comment]
Hi @DenisVuyka,

we tried the categories and it works half-and-half. The downside is:
- The buckets don't show the number of results matching that bucket
- Selecting a bucket doesn't trim down the available buckets to only those that have matching results
- Buckets are shown which don't have a matching result
- If you click such a bucket, the screen goes blank.

I do think adding the bucket-option to the facets is a must.

**Comment by suzanadirla** [comment]
Hi @HansDeBal,
We will investigate the problems you mentioned and in order to see the count numbers for the buckets you could use this approach:
``` "facetQueries": {
            "label": "SEARCH.CATEGORIES.MODIFIED_DATE",
            "queries": [
                { "label": "Today", "query": "cm:modified:[TODAY to TODAY]" },
                { "label": "This week", "query": "cm:modified:[NOW/DAY-7DAYS TO NOW/DAY+1DAY]" },
                { "label": "This month", "query": "cm:modified:[NOW/DAY-1MONTH TO NOW/DAY+1DAY]"},
                { "label": "In last 6 months", "query": "cm:modified:[NOW/DAY-6MONTHS TO NOW/DAY+1DAY]"},
                { "label": "This year", "query": "cm:modified:[NOW/DAY-1YEAR TO NOW/DAY+1DAY]"}
            ]
        },
```

**Comment by yregaieg** [comment]
Hey @suzanadirla ,

We have tried that as well, but unfortunately, unlike categories, facetQueries do not support facets grouped under multiple groups when we need to have facets related to different fields (ie: creationDate, submissionDate ...).
We also noticed that facetQueries label is not working (at least not for ADF 2.4 which we are currently using)

**Comment by suzanadirla** [comment]
Indeed, at the moment the grouped facetQueries are not supported in ADF, but the good news is that since ACS 5.2.1 there is API support for grouped facet queries and also for facetIntervals as found [here](https://community.alfresco.com/people/andy1/blog/2017/10/02/basic-content-reporting-using-the-521-search-api) and
new ADF tickets have been created to include support for grouped facet queries and facet intervals.
I do not know what is the priority for these ones and when they will be done, but ADF is open source and [contributions](https://github.com/Alfresco/alfresco-ng2-components/wiki/Code-contribution-acceptance-criteria) are welcomed.

**Comment by eromano** [comment]
I like it , contribute from the community will be welcomed  😄

**Comment by HansDeBal** [comment]
@eromano any idea is this could be added to ADF 2.6? It's quite important for our current project...

**Comment by suzanadirla** [comment]
This feature request is completed because now the grouped facetQueries are supported starting with [ADF 3.0.0 version](https://www.alfresco.com/abn/adf/docs/release-notes/relnote300/#grouped-facet-queries) and the facetIntervals are supported starting with [ADF 3.1.0 version](https://www.alfresco.com/abn/adf/docs/release-notes/relnote310/#facet-intervals)
