### ISSUE TITLE
Viewer is really slow in rendering large files

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#420]

**Comment by hashraf88** [comment]
[Uploading Patrick Niemeyer, Daniel Leuck - Learning Java, 4th Edition - 2013.pdf.zip…]()

**Comment by eromano** [comment]
Turns out that the performance problem is relative to the data table.
The data table is used inside the document list and it has inside the class ShareDataTableAdapter that is using the 50% of the CPU  in this method getValue(row: DataRow, col: DataColumn).
The document list is everytime on also when we show a file in the viewer,  so this background process is eating the 50% of the resources.
I am going to open a separate bug about this issue.
As a workaround I I will just hide the document list when we open a file but this thing has as side effect to show for a second the empty folder view when we close the viewer.

**Comment by DenisVuyka** [comment]
I also suggest investigating modal dialogs and rendering elements on top of other elements. It may happen that the rendering problem is because of the modal overlay and angular renderer trying to still operate on background (like the mouse events that document list received when viewer was enabled). As for now hiding document list is fine.
