### ISSUE TITLE
Preview of documents attached APS process does not work

### ISSUE THREAD

**Issue by alfsender** [Alfresco/alfresco-ng2-components#5137]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
I am using ADF 3.4 version. When I try to open any task of APS which has document (word document) attached, in ADF I see document with option to "view" the document. When I click on view it calls "rendition" API of APS. but in Rendition Type ADF is not passing correct value, so API call is failing.

I tried with demo-shell app as well and I am seeing same issue. below is the URL that gets generated activiti-app/api/enterprise/content/115132/rendition/%7BrenditionType%7D
in this URL it should pass preview instead of %7BrenditionType%7D. If i change it to preview and open url in browser I am able to preview the document.

**Expected behavior:**
ADF should pass renditionType as "preview" and load the document preview

**Steps to reproduce the issue:**
- start an APS process with word document attached and assign a task to user.
- Open the task from ADF, on document attached process click on "show" action to preview the document.

**Component name and version:** 
- adf-viewer
- ADF version 3.4

**Browser and version:** 
Chrome

**Node version (for build issues):**  
Node 8.16.1

**New feature request:**

**Comment by alfsender** [comment]
Hi Team,

Just wanted to check is there a workaround which I can apply to fix this issue? I am running ADF version 3.4.0 in my project. 

Thanks.

**Comment by dhrn** [comment]
Hi @alfsender ,

we will try to address the scenario as soon as possible. here is the existing ticket (https://issues.alfresco.com/jira/browse/ADF-4055)

Thanks

**Comment by dhrn** [comment]
**Workaround**:  upload from the user-owned/accessible site.
**Note**: Don't use the public site to upload the content. and make sure the user has authenticated to repositories in the activiti app(profile section).

![image](https://user-images.githubusercontent.com/14145706/69123777-39579700-0ac8-11ea-810b-bfb7f7289752.png)

**Comment by mbuyukkalender** [comment]
Hello @dhrn ,

This workaround doesn't work for the preview of a document from a task-detail component in ADF.

We already have the same issue as you can see in the attachments :

![Capture d’écran 2019-11-21 à 08 53 31](https://user-images.githubusercontent.com/56829773/69319398-667a8580-0c3f-11ea-8089-5edbb7c43365.png)
![Capture d’écran 2019-11-21 à 09 12 52](https://user-images.githubusercontent.com/56829773/69319415-6bd7d000-0c3f-11ea-99a5-b78cc1e50662.png)
![Capture d’écran 2019-11-21 à 09 11 24](https://user-images.githubusercontent.com/56829773/69319427-72664780-0c3f-11ea-9f47-458710d506fc.png)

**Comment by dhrn** [comment]
please make sure you are getting an icon like this

![image](https://user-images.githubusercontent.com/14145706/69320529-61313100-0c67-11ea-820d-c5ee3bc95246.png)

After that, Try upload using activiti-app to make sure your configuration is fine.

Then Use ADF with the same scenario( it is working for me)

Note: the problem here is ADF is not filtering the sites(it is showing all the sites). when you upload a file that is not an authorized folder/file, it is failing silently. then you will get 404.

**Comment by mbuyukkalender** [comment]
@dhrn ,

Everything works fine from an APS point of view. If I play the process from APS, I have the preview and I can even edit the document with MS Word without issue....

The problem is on the ADF side... And what you noticed isn't relevant for me, because the user who access to the task is an administrator and also a member of the site (as a manager) where the document is picked up.

**Comment by dhrn** [comment]
can you share a sandbox app for better understanding?

**Comment by alfsender** [comment]
@dhrn This issue is in ADF when previewing document which is attached to process. (note: when you try to preview this document from APS it works).
I also checked from demo-shell app which comes with ADF, even it has the same issue. So, this would require fix in ADF framework which makes API call to preview the document attached to process.

**Comment by eromano** [comment]
@alfsender can you try in ADF 3.7.0?

**Comment by alfsender** [comment]
@eromano apologies for delay in response. I just tested and see it works in ADF 3.7.0. Thank you.
