### ISSUE TITLE
Japanese Translation

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/alfresco-ng2-components#5411]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [x] Documentation

**New documentation request:**
Do you plan to make the documentation multilingual?

In PR https://github.com/Alfresco/alfresco-content-app/pull/1186 , I converted the Alfresco Content App documentation into Japanese, so I hope the same ADF documentation can be used.

**Comment by fcorti** [comment]
Hi @silverskyvicto,

I'm @fcorti, Product Manager for ADF.
Thank you for raising the question that might help many Japanese speakers.
Unfortunately the translation of the ADF documentation in Japanese is not included in our short term plan, but I'm happy to add it to the "todo" list.

Would be great to hear from other Japanese speakers how many of you would need this task to be done, why is important and which benefit can be for your goals.
Of course, I can imagine the answers to the questions above, but it is always better to hear for a direct feedback instead of "guessing".

Cheers.

**Comment by silverskyvicto** [comment]
Hi @fcorti 

Understood.
