### ISSUE TITLE
Support for Video files in Viewer

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#603]
Provide support for displaying Video files in the Viewer component via html5 **video** element.

**Comment by hashraf88** [comment]
Tested on Safari, Chrome and Firefox.
**Supported**
Mp4 fine in all borwsers
WebM works for Firefox and Chrome only
Ogv works for Firefox and Chrome only

**Unsupported** (do not work unless stated otherwise)
AVI
ASF
Mov/QT (only functions in Safari)
Flv

For video types that are unsupported we should have a message similar to that for unsupported document types. Currently the below is displayed and could cause confusion. 
![screen shot 2016-09-05 at 15 58 51](https://cloud.githubusercontent.com/assets/13200338/18251571/ad7f0852-7381-11e6-87d5-89025a35ba3e.png)
