### ISSUE TITLE
DST is not taken into consideration in timestamps

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#659]
Daylight Saving Time (DST) not taken into consideration in timestamps
Currently timestamps are using Greenwich Mean Time (GMT) and not 

British Summer time = GMT+1 
British Winter time = GMT
1. Upload a file in document
2. Notice time stamp is GMT not GMT+1

E.g. DST is 10:30, timestamp is 9:30

**Comment by wabson** [comment]
This will be fixed by #133 when the changes there are merged.

All date/times are now timezone-aware and should be now shown relative to the user's *current* timezone. This means BST between April-October in the UK, so this fixes the issue described here.

One quirk of this is that during BST all times shown will be in BST, even if it was GMT at the time of the event occurring, and vice versa. This would be another task to consider if we need to display times according to the user's current *locale*, rather than their current *timezone*.

The changes there affect all date properties passing through the JS-API layer, so it is worth testing some Activiti process instances/tasks as well as the document list, as I have done myself.

As we are now outside of BST I tested by changing my computer's timezone to EST (New York) and checking that on reloading the document-list that the folder creation time was 5 hours earlier that before.

**Comment by davidcognite** [comment]
> One quirk of this is that during BST all times shown will be in BST, even if it was GMT at the time of the event occurring, and vice versa.

That shouldn't be the case with an ISO8601 date time. The TZ offset should correctly represent the daylight saving time for a given timezone at the relevant point in time.

**Comment by wabson** [comment]
Thanks @davidcognite, that makes sense if what you are saying is that the date recorded on and returned by the server is timezone-aware and therefore definitive but I was referring to the way we currently render dates in the UI, which is based on the current timezone offset in the browser rather than trying to work out what time it would have said on the user's watch when the event occurred.

For example a folder created at `2016-10-29T17:00:00` would render as '5:00:00 PM' in the browser until the DST change that evening, then subsequently it would show was '4:00:00 PM'.

Perhaps in the future we may want to use something like [moment timezone](http://momentjs.com/timezone/) to improve on this.
