### ISSUE TITLE
If task is claimed does not display under my/involved tasks

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#718]
1. Start a process, which includes at least one user task that is not auto assigned
2. Claim task
3. Login to demo app with same user and go to activiti task list

**Expected**
Task is displayed under my/involved tasks in demo app
**Actual**
Task is not displayed under my/involved tasks in demo app

**Comment by mauriziovitale** [comment]
The problem is that the demo shell doesn’t give the possibility to select a deployed app in activiti before use tasks/process. Actually, the applicationId in the demo shell is alway null. 
We need a feature that provides this component.

As a basic test, I will provide an url where you can put manually the appId to filter the tasks just to see if the API works fine with the appId parameters. 

Something like 
http://0.0.0.0:3000/activiti/appId/1001

**Comment by hashraf88** [comment]
Unfortunately task does not display when using url pointing at specific app e.g.http://localhost:3000/activiti/appId/1004
