### ISSUE TITLE
Investigate which private APIs are being used

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#729]
We know the people/user form component for Activiti uses a private REST API.

Obviously we need to use the public APIs, but there are cases where we simply don't have them yet.

In this case we need to be absolutely clear about where/how and **why** we are using the private APIs.

For this ticket we only want to get clarity and list the uses of private APIs.

**Comment by DenisVuyka** [comment]
Group picker widget:
`/activiti-app/app/rest/workflow-groups?filter=${filter}&groupId=${groupId}`

People picker widget:
`/activiti-app/app/rest/workflow-users?filter=${filter}&groupId=${groupId}`

**Comment by DenisVuyka** [comment]
[Documentation](https://docs.alfresco.com/activiti/docs/dev-guide/1.5.0/) seems to have got updated with additional APIs that can be used instead of the private ones (needs review):

Group picker widget:
`GET api/enterprise/process-instances/{processInstanceId}/identitylinks/groups`

People picker widget:
`GET api/enterprise/process-instances/{processInstanceId}/identitylinks/users`

Attach widget:
`POST api/enterprise/process-instances/{taskId}/raw-content`

Widget visibility service:
`GET api/enterprise/process-instances/{processInstanceId}/variables`

**Comment by DenisVuyka** [comment]
Reopening the issue as it is not fixed, just hidden inside `alfresco-js-api`.

**Comment by tdonovancsra** [comment]
What's the status of this?  I notice 1.5 still calls the private API '/app/rest/task-forms/{taskId}/variables', 'GET',   This has become a real problem for us.    
+10

**Comment by eromano** [comment]
There is a PR for 1.6.0 of the alfresco-js-api that solve this problem .On the  PR https://github.com/Alfresco/alfresco-js-api/pull/231  you can find the fix. If you want you can start to use this version of the js api installing it on your project and test it. 

Should be enough do in order to test it :

```
npm install git://github.com/Alfresco/alfresco-js-api.git#9f191a89664f2d59d53434e796aa84c17d1bee2c
```

**Comment by DenisVuyka** [comment]
And I believe you will need Activiti 1.6.1 for that.

**Comment by tdonovancsra** [comment]
Great thanks for the input.  Let me see about upgrading our backend
